In [1]:
import numpy as np

In [2]:
myNp_list=np.arange(0,10)

In [3]:
myNp_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
myNp_list[5]

5

In [5]:
myNp_list[:4]

array([0, 1, 2, 3])

BURADA EŞİTLEME YAPTIK

In [6]:
myNp_list[:4]=-2

In [7]:
myNp_list

array([-2, -2, -2, -2,  4,  5,  6,  7,  8,  9])

# DİZİDEN PARÇA ALMAK

In [8]:
yeni_dizi=np.arange(0,20)
yeni_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
parca_dizi=yeni_dizi[3:7]
parca_dizi

array([3, 4, 5, 6])

In [10]:
parca_dizi[:]=102

BURADA yeni_dizi DEN ALDIĞIMIZ PARÇADAKİ DEĞİŞİKLİK yeni_dizi Yİ DE ETKİLEDİ

In [11]:
yeni_dizi

array([  0,   1,   2, 102, 102, 102, 102,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

BUNUN İÇİN BİR YÖNTEM VAR

BURADA yeni_parca_dizi YE KOPYALIYORUZ. ORADAN PARÇA ALIYORUZ. yeni_parca_dizi ETKİLENİYOR. ORİJİNAL DİZİ ETKİLENMİYOR.

In [12]:
yeni_dizi2=np.arange(0,20)
yeni_kopya_dizi=yeni_dizi2.copy()

In [13]:
yeni_kopya_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
yeni_parca_dizi=yeni_kopya_dizi[5:15]

In [15]:
yeni_parca_dizi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
yeni_parca_dizi[:]=94

In [17]:
yeni_parca_dizi

array([94, 94, 94, 94, 94, 94, 94, 94, 94, 94])

yeni_kopya_dizi ETKİLENDİ

In [18]:
yeni_kopya_dizi

array([ 0,  1,  2,  3,  4, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 15, 16,
       17, 18, 19])

yeni_dizi2 ETKİLENMEDİ

In [19]:
yeni_dizi2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# INDEXLEME DETAY

In [50]:
my_list=np.array([[3,4,5],[1,2,3],[7,6,8]])
my_list

array([[3, 4, 5],
       [1, 2, 3],
       [7, 6, 8]])

BU my_list[1][2] İLE AYNI

In [51]:
my_list[1,2]

3

[  ] BU ŞEKİLDE PARAMETRE VERİRSEK SATIR DÖNDÜRÜR

In [53]:
my_list[[1,2]]

array([[1, 2, 3],
       [7, 6, 8]])

In [49]:
my_list[[2,0]]

array([[7, 6, 8],
       [3, 4, 5]])

# OPERASYONLAR 

In [56]:
new_list=np.random.randint(0,100,20)
new_list

array([14, 54, 55, 30, 94, 10, 53, 94, 64, 13, 54, 11, 93, 36, 54, 86, 49,
       93, 46, 35])

In [58]:
for x in new_list:
    if x>60:
        print(x)

94
94
64
93
86
93


VEYA

In [66]:
result_new_list=new_list > 90
result_new_list

array([False, False, False, False,  True, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False])

SONUÇ DİZİSİNİ İNDEX GİBİ DİZİYE VERİRSEK FİLTRELEME YAPAR.

In [67]:
new_list[result_new_list]

array([94, 94, 93, 93])

In [68]:
new_list*2

array([ 28, 108, 110,  60, 188,  20, 106, 188, 128,  26, 108,  22, 186,
        72, 108, 172,  98, 186,  92,  70])

In [69]:
new_list/3

array([ 4.66666667, 18.        , 18.33333333, 10.        , 31.33333333,
        3.33333333, 17.66666667, 31.33333333, 21.33333333,  4.33333333,
       18.        ,  3.66666667, 31.        , 12.        , 18.        ,
       28.66666667, 16.33333333, 31.        , 15.33333333, 11.66666667])

In [71]:
new_list

array([14, 54, 55, 30, 94, 10, 53, 94, 64, 13, 54, 11, 93, 36, 54, 86, 49,
       93, 46, 35])

In [75]:
new_list**2

array([ 196, 2916, 3025,  900, 8836,  100, 2809, 8836, 4096,  169, 2916,
        121, 8649, 1296, 2916, 7396, 2401, 8649, 2116, 1225], dtype=int32)

VEYA power() KULLANARAK İSTEDİĞİMİZ KADAR ÜS ALABİLİRİZ. 

power(DİZİ/DEĞER , ÜS DEĞERİ)

In [80]:
np.power(new_list,2)

array([ 196, 2916, 3025,  900, 8836,  100, 2809, 8836, 4096,  169, 2916,
        121, 8649, 1296, 2916, 7396, 2401, 8649, 2116, 1225], dtype=int32)

BU DA OLUR square() KARESİNİ ALIR.

In [79]:
np.square(new_list)

array([ 196, 2916, 3025,  900, 8836,  100, 2809, 8836, 4096,  169, 2916,
        121, 8649, 1296, 2916, 7396, 2401, 8649, 2116, 1225], dtype=int32)

In [77]:
np.power(new_list,1/2)

array([3.74165739, 7.34846923, 7.41619849, 5.47722558, 9.69535971,
       3.16227766, 7.28010989, 9.69535971, 8.        , 3.60555128,
       7.34846923, 3.31662479, 9.64365076, 6.        , 7.34846923,
       9.2736185 , 7.        , 9.64365076, 6.78232998, 5.91607978])

VEYA sqrt() YAPABİLİRİZ. DİREK KÖK ALIR.

In [78]:
np.sqrt(new_list)

array([3.74165739, 7.34846923, 7.41619849, 5.47722558, 9.69535971,
       3.16227766, 7.28010989, 9.69535971, 8.        , 3.60555128,
       7.34846923, 3.31662479, 9.64365076, 6.        , 7.34846923,
       9.2736185 , 7.        , 9.64365076, 6.78232998, 5.91607978])