BURADA numpy ı DİREK np DİYE KISALTTIK KULLANIMDA KOLAYLIK SAĞLAR

In [36]:
import sys
!{sys.executable} -m pip install numpy

In [37]:
import numpy as np

# numpy array 

In [38]:
mylist=[1,2,3,4,5,6]
my_numpy_list = np.array(mylist)

In [39]:
type(my_numpy_list)

numpy.ndarray

 NUMPY İLE MATRİS YAPALIM 

In [40]:
my_matris_list=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [41]:
my_matris_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

3x4 LÜK MATRİS OLDU 3 SATIR 4 SÜTUN

In [42]:
np.array(my_matris_list)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# arange listelerde range numpy arraylerinde arange gibi düşün

# ÖNEMLİ !!

In [43]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(0,20,5)
# başlangıç noktası,bitiş noktası,artış miktarı

array([ 0,  5, 10, 15])

# zeros 0 array i yapar

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

(2,2) YAPARSAK 2x2 LİK 0 MATRİSİ YAPAR

In [46]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [47]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# ones 1 matrisi yapar. zerosla aynı

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace (başlangıç,bitiş,kaç değere bölünecek) 

# ÖNEMLİ !!!

0 İLE 10 ARASINA EŞİT DAĞILAN 8 DEĞERE SAHİP ARRAY OLUŞTURDU.

In [50]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

# eye üst ve alt 0, orta köşegen 1 matris yapar.

In [51]:
np.eye(4) # köşegen matris

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# random

random 8 değere sahip array döndürdü

In [52]:
np.random.randn(8)

array([-0.5505903 ,  0.33320658, -0.96420645,  0.0082792 ,  0.51469695,
       -0.45226883,  0.82027658,  0.42831686])

bu sefer 3x3 random array döndürdü

In [53]:
np.random.randn(3,3)

array([[ 0.25320237,  0.1223963 ,  0.88039757],
       [-0.60756617, -0.18512954, -0.72887831],
       [-3.00789438,  1.28956692, -1.52039612]])

int döndürür/array yapar (alt sınır, üst sınır, değer sayısı)

In [54]:
np.random.randint(1,10,2)

array([6, 9])

In [55]:
my_random_int_list=np.random.randint(1,100,10)

In [56]:
my_random_int_list

array([60, 57, 71, 14, 25, 55, 94, 84, 88, 77])

In [57]:
for random_value in my_random_int_list:
    print(random_value)

60
57
71
14
25
55
94
84
88
77


# numpy dizi metodları

In [58]:
numpy_dizi=np.arange(0,20)

In [59]:
numpy_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
type(numpy_dizi)

numpy.ndarray

# reshape numpy arrayi matris yapar
# 20 sayılık matrisi 5x6 yapamaz 5x4 yapabilir

In [61]:
numpy_dizi.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

numpy_dizi.reshape(5,6)


ValueError: cannot reshape array of size 20 into shape (5,6)

In [62]:
numpy_dizi.max()

19

In [63]:
my_random_int_list.max()

94

In [64]:
numpy_dizi.argmax()

19

In [65]:
my_random_int_list.argmax()

6

In [66]:
my_random_list.argmax()

NameError: name 'my_random_list' is not defined